[build]
command="npm install --build-from-source=canvas && npm run build:netlify"
functions="dist/lambdas"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/handler"
  status = 200
  force = true